instance of PG_Provider
{
	ProviderModuleName = "UNIXProvidersModule";
	Name = "UNIX_Specific802dot1QVLANServiceProvider";
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_Specific802dot1QVLANServiceProvider";
	ClassName = "CIM_Specific802dot1QVLANService";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_Specific802dot1QVLANServiceProvider";
	ClassName = "UNIX_Specific802dot1QVLANService";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

