instance of PG_Provider
{
	ProviderModuleName = "UNIXProvidersModule";
	Name = "UNIX_DatabaseStorageAreaProvider";
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseStorageAreaProvider";
	ClassName = "CIM_FileSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseStorageAreaProvider";
	ClassName = "UNIX_FileSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseStorageAreaProvider";
	ClassName = "CIM_DatabaseStorageArea";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseStorageAreaProvider";
	ClassName = "UNIX_DatabaseStorageArea";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

