instance of PG_Provider
{
	ProviderModuleName = "UNIXProvidersModule";
	Name = "UNIX_FCPortProvider";
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_FCPortProvider";
	ClassName = "CIM_NetworkPort";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_FCPortProvider";
	ClassName = "UNIX_NetworkPort";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_FCPortProvider";
	ClassName = "CIM_FCPort";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_FCPortProvider";
	ClassName = "UNIX_FCPort";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

