instance of PG_Provider
{
	ProviderModuleName = "UNIXProvidersModule";
	Name = "UNIX_DatabaseSystemProvider";
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseSystemProvider";
	ClassName = "CIM_ApplicationSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseSystemProvider";
	ClassName = "UNIX_ApplicationSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseSystemProvider";
	ClassName = "CIM_DatabaseSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_DatabaseSystemProvider";
	ClassName = "UNIX_DatabaseSystem";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

