instance of PG_Provider
{
	ProviderModuleName = "UNIXProvidersModule";
	Name = "UNIX_VideoBIOSFeatureProvider";
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_VideoBIOSFeatureProvider";
	ClassName = "CIM_SoftwareFeature";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_VideoBIOSFeatureProvider";
	ClassName = "UNIX_SoftwareFeature";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_VideoBIOSFeatureProvider";
	ClassName = "CIM_VideoBIOSFeature";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
	ProviderModuleName = "UNIXProvidersModule";
	ProviderName = "UNIX_VideoBIOSFeatureProvider";
	ClassName = "UNIX_VideoBIOSFeature";
	Namespaces = {"root/cimv2"};
	ProviderType = { 2,5,7 };
	SupportedProperties = NULL; // All properties
	SupportedMethods = NULL; // All methods
};

